### ISSUE TITLE
Develop content for the Help page of GCconsultation

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/GCconsultation#9]
The general help material for GCconsulation will be posted on Fresdesk directly. We need to develop text for the help page of GCconsultation (https://consul.beta.gccollab.ca/help), which will include a link to the new Freshdesk portal for GCconsulation. (Link to portable to come). 

Note: dependent on completion of: [Zube #3757](https://zube.io/tbs-sct/gctools/c/3757)

**Comment by LemieuxGen** [comment]
Some content is being developed by Partnerships team: https://docs.google.com/document/d/10VbgbsviHUCu6fKAutynYRL3IfB5VLgf-Ax3lcZ_We8/edit?ts=5c38d214

To be determined who is leading and what are the gaps. 
@PhilAndrecheck can you confirm?

**Comment by MGoodberry** [comment]
@LemieuxGen For review
[GCcon Help page content.docx](https://zube.io/files/tbs-sct/526fc5a7a8ee8a5f229f5fcf611046ea-gccon-help-page-content.docx)

**Comment by MGoodberry** [comment]
Reopened because the functionalities have changed.

**Comment by s-duffey** [comment]
No longer an application we are working on.
